dist: xenial

language: go

go:
- 1.x

git:
  depth: 1

notifications:
  email: false

branches:
  only:
  - master

script: go build

before_deploy:
  - git config --local user.name "OrangeFlare"
  - git config --local user.email "josef@baltz.net"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%y.%m.%d.%H%M%S')}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: OfOJTnAWAAjgk7QqcXD+OxiytyyDOj0BBtiEHBcLphUawMy93Zfb/fVFM9T+uvy8BFPRjhwUcwy0HEUKcEx12njWnkQWQx2B83H6UCVpDXgXGYy/bzaBhdHfu3UFJR4ezxlvsYl02wOhX6B1/6RcTdsjH2lKN2KeklAYdmErk5AB1OvYCjruayqkvbo6Nngg4lVVfhkK1Q6J+TDOwxwo6uVLj4YW2drQFPPckTLh3GdBIHfKTGNACiyh+FhCwadnn1Xygu7HGwujQJDEtuY1AmwVsLPJp87fjScw3f+CiYHGp/BOY/brn78455eIsLCFELwfupCN2zQkPmcho1/oFa74oW2p2u7MNc34HZdcV6Orxx4jxqgbP/tgopo4f4yAQC3Rw1pys3lNCk/rqdREytMfQ7s29KNH2M2BUEpOfqatuFH5HrOFwVCeGXI/4NGUp63YX2JpVSWC89bse/UDGIVvJxT/5InsQI7UznT33PpA19HcJyYQpJXhol+fLyZ6t/RAl9eGN5hgPnwqeWINLdT3pVm9B7PHiPGShE5OdZLPQDYWeZR2Yzx3RVAbIGAYELcNHQnn6WiHz1W2xeVR//DlrtIRts6nQmU48Yv2vtotOW+sOMxg3Vkmu+NZ7m2jvF94Qo8hJ3neAPtvOQJhX/H5ESqxhHBVjIhGlYiXbZg=
  file: Wumpagotchi
  on:
    repo: OrangeFlare/Wumpagotchi